version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: simple_chat
    ports:
      - "5432:5432"
    volumes: 
      - dbdata:/var/lib/postgresql/data

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - ./backend/:/app/
    depends_on:
      - postgres
      - redis 
    working_dir: "/app"
    expose:
      - 8000
    ports:
      - "8000:8000"
    command: "python manage.py runserver 0.0.0.0:8000"

  redis:
    image: redis:5  
    container_name: redis
    expose:
      - 6379 
    volumes:
      - redisdata:/data 

  # pg-admin:
  #   image: dpage/pgadmin4:6
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@email.com
  #     - PGADMIN_DEFAULT_PASSWORD=admin
  #     - PGADMIN_LISTEN_PORT=5050
  #   ports:
  #     - "5050:5050"
  frontend:
    image: node:19 
    container_name: frontend
    working_dir: /app
    volumes:
      - frontend_files:/frontend/dist
      - ./frontend:/app 
    ports:
      - "8080:8080" 
    command: npm run dev
  nginx:
    build:
      context: .
      dockerfile: ./dockers/nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./frontend/dist/:/home/app/frontend_files
    depends_on:
      - frontend
      - backend

volumes:
  dbdata:
  redisdata:
  static_files:
  frontend_files: