version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: simple_chat
    ports:
      - "5432:5432"
    volumes: 
      - dbdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: ./backend/.env
    restart: always
    volumes:
      - ./backend/:/app/
    depends_on:
      - postgres
      - redis  # Add dependency on the Redis service
    working_dir: "/app"
    expose:
      - 8000
    ports:
      - "8000:8000"
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

  redis:
    image: redis:5  # Use Redis version 5 image
    container_name: redis
    expose:
      - 6379  # Expose Redis port for communication with other services
    volumes:
      - redisdata:/data  # Use a volume to persist Redis data

  pg-admin:
    image: dpage/pgadmin4:6
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"

volumes:
  dbdata:
  redisdata:
