# Generated by Django 4.1.4 on 2023-07-19 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='user_id',
            new_name='user_from',
        ),
    ]
