# Generated by Django 4.1.4 on 2023-07-20 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_rename_user_id_conversation_user_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
