# Generated by Django 4.1.4 on 2023-07-20 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0006_alter_chat_conversation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_seen',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='user_send',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
