# Generated by Django 4.1.4 on 2023-07-20 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_conversation_is_seen_conversation_user_send'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='user_send',
        ),
    ]
