# Generated by Django 4.2.3 on 2023-07-27 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_groupchat_member_conversation_group_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='group',
            new_name='group_id',
        ),
    ]
