# Generated by Django 4.2.3 on 2023-07-28 08:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_alter_member_user_id_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user_email_chat',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='group_id',
            field=models.CharField(default='fsgdghd-dghdgh-dhdghdg-dhdghg', max_length=255),
            preserve_default=False,
        ),
    ]
