# Generated by Django 4.2.3 on 2023-07-28 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_rename_conent_notification_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='user_email_chat',
            new_name='email_user_chat',
        ),
    ]
