# Generated by Django 4.2.3 on 2023-07-28 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_rename_user_email_chat_notification_email_user_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='is_seen',
        ),
    ]
