# Generated by Django 4.2.3 on 2023-07-28 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_conversation_list_user_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='is_sent',
        ),
    ]
