# Generated by Django 4.2.3 on 2023-07-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_conversation_list_message_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_seem',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
