# Generated by Django 4.2.3 on 2023-07-30 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0020_notification_is_seem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='group_id',
        ),
        migrations.AddField(
            model_name='notification',
            name='conversation_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_conversation', to='chat.conversation'),
        ),
    ]
