# Generated by Django 4.2.3 on 2023-08-07 09:04

import chat_base.core.constants.related_name
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name=chat_base.core.constants.related_name.RelatedName['NOTIFICATION_USER'], to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='member',
            name='group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name=chat_base.core.constants.related_name.RelatedName['MEMBER_GROUP'], to='chat.groupchat'),
        ),
        migrations.AddField(
            model_name='member',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name=chat_base.core.constants.related_name.RelatedName['USER_MEMBERS'], to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='groupchat',
            index=models.Index(fields=['id'], name='groupchats_id_5411fa_idx'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name=chat_base.core.constants.related_name.RelatedName['CONVERSATION_GROUP'], to='chat.groupchat'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='user_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name=chat_base.core.constants.related_name.RelatedName['USER_FROM_CONVERSATIONS'], to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='user_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name=chat_base.core.constants.related_name.RelatedName['USER_TO_CONVERSATIONS'], to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='conversation_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name=chat_base.core.constants.related_name.RelatedName['CHAT_CONVERSATION'], to='chat.conversation'),
        ),
        migrations.AddField(
            model_name='chat',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name=chat_base.core.constants.related_name.RelatedName['CHATS_USER'], to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['id'], name='notificatio_id_d0ee49_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['id'], name='members_id_7cd900_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['id'], name='conversatio_id_2eadd3_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['id'], name='chats_id_e6f9d1_idx'),
        ),
    ]
